### ISSUE TITLE
Ability to separate surname and given name

### ISSUE THREAD

**Issue by ottlngr** [ottlngr/bib2df#4]
This might help: https://cran.r-project.org/web/packages/humaniformat/index.html

**Comment by ottlngr** [comment]
Implemented in the dev-names branch. Do you want to try it, @leeper ?

**Comment by leeper** [comment]
Nice! Works great. Only thing would be whether you want to use snake case rather than camel case for the argument name, given the functions all use snake case. I don't think this really matters but just in case you're concerned about consistency.
