### ISSUE TITLE
submitting bib2df to rOpenSci?

### ISSUE THREAD

**Issue by maelle** [ottlngr/bib2df#7]
This is not an academic spam I promise. 😄 

Have you considered submitting this package to rOpenSci onboarding process? More info [here](https://github.com/ropensci/onboarding) + I can answer any question. 

In brief, onboarding is an open review process, with often two reviewers having a look at the package according to the guidelines. I'm a co-editor now so I might sound biased but I've submitted a few packages before that and I've really learned a ton & improved the packages. Onboarded packages then live in the ropensci organization on Github but you're still the maintainer and keep admin rights to the repository. Your package seems to fit in the data extraction category.

And obviously no problem if you prefer not to submit `bib2df`!

**Comment by ottlngr** [comment]
I thought about that already two weeks ago when I released v0.2, but went on holiday just after that. Now I'm back and willing to go through the first steps. Probably will have to do some minor changes and additions first to fulfill the policies/guidelines.

Got to have to check out `RefManageR` in detail, but I think it has a different scope.

**Comment by ottlngr** [comment]
**Agenda:**

- [x] Add vignette
- [ ] Check similarities/differences regarding `RefManageR`
- [ ] Add `CONDUCT.md`
- [ ] Add top-level documentation `?bib2df`
- [ ] Add `NEWS.md`
- [ ] Add @maelle to `Authors@R` (if she agrees)
- [ ] More tests necessary?
- [ ] Add `codecov`
- [ ] Check messages, warnings and errors

**Comment by maelle** [comment]
I can be a ctb, although my contribution was really small :wink: thank you!

**Comment by ottlngr** [comment]
Done.

**Comment by maelle** [comment]
Thanks!
